---

- name: main > Include "{{ ansible_os_family|lower }}" vars
  include_vars:
    file: "{{ ansible_os_family|lower }}/main.yml"

- name: main > Include "{{ ansible_os_family|lower }}" tasks
  include: "{{ ansible_os_family|lower }}/main.yml"
  static: false
  tags:
     - manala_locales
