---

# Install
- include: install.yml
  tags:
    - manala_locales

# Codes
- include: codes.yml
  when: manala_locales_codes|length
  tags:
    - manala_locales

# Codes Defaults
- include: codes_default.yml
  when: manala_locales_codes_default is not none
  tags:
    - manala_locales
