---

# Install
- include: install.yml
  tags:
    - manala_locales

# Codes
- include: codes.yml
  when: manala_locales_codes|length
  tags:
    - manala_locales

# Codes Defaults
- include: codes_default.yml
  # see https://github.com/ansible/ansible/issues/20392
  when: manala_locales_codes_default|default('') != ''
  tags:
    - manala_locales
